package com.relay.common.dto

import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.NotEmpty
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size

/**
 * The gateway → call-service signaling contract. One request per verb rather than one request
 * with nullable fields for all of them: the state machine validates differently per verb, and a
 * shape that cannot express `accept` without an SDP is worth more than four saved data classes.
 *
 * `userId` and `sessionId` are taken from the authenticated socket by the gateway and are
 * **trusted** here, which is why these endpoints live under `/internal` and must never be routed
 * by the api-gateway.
 *
 * `callId` is generated by the *client*, not the server. The caller's trickle ICE starts arriving
 * before any server round trip could hand back an id, so candidates need an id that exists from
 * the first millisecond — and a repeated one makes a retried invite a primary-key collision the
 * service can answer with the call it already stored.
 */

/** `audio` or `video`. Anything else is a client bug, not a negotiable request. */
private const val MEDIA_PATTERN = "audio|video"

data class InviteCallRequest(

    @field:NotBlank
    @field:Size(max = 64)
    val callId: String,

    @field:NotBlank
    @field:Size(max = 64)
    val callerId: String,

    @field:NotBlank
    @field:Size(max = 64)
    val calleeId: String,

    @field:NotBlank
    @field:Size(max = 64)
    val sessionId: String,

    @field:Pattern(regexp = MEDIA_PATTERN)
    val media: String,

    /** The caller's SDP offer, relayed verbatim. The server never parses it. */
    @field:NotBlank
    val sdp: String,

    /** Optional client-side correlation to a dialog. Stored, never validated — call-service
     *  cannot see message-service's dialogs and must not try. */
    val dialogId: String? = null
)

data class AcceptCallRequest(

    @field:NotBlank
    @field:Size(max = 64)
    val userId: String,

    @field:NotBlank
    @field:Size(max = 64)
    val sessionId: String,

    /** The callee's SDP answer. */
    @field:NotBlank
    val sdp: String
)

data class RejectCallRequest(

    @field:NotBlank
    @field:Size(max = 64)
    val userId: String,

    @field:NotBlank
    @field:Size(max = 64)
    val sessionId: String,

    @field:Size(max = 32)
    val reason: String? = null
)

data class IceCandidateRequest(

    @field:NotBlank
    @field:Size(max = 64)
    val userId: String,

    @field:NotBlank
    @field:Size(max = 64)
    val sessionId: String,

    /** Opaque `RTCIceCandidateInit`. Relayed verbatim; the server reads nothing inside it. */
    @field:NotEmpty
    val candidate: Map<String, Any?>
)

data class HangupCallRequest(

    @field:NotBlank
    @field:Size(max = 64)
    val userId: String,

    @field:NotBlank
    @field:Size(max = 64)
    val sessionId: String,

    @field:Size(max = 32)
    val reason: String? = null
)
