package com.relay.common.dto

import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.Size

/**
 * Contract between websocket-gateway and message-service.
 *
 * [clientMessageId] is generated by the client and is what makes sending idempotent. A send that
 * succeeded but whose acknowledgement was lost will be retried over REST, and message-service
 * must recognise the retry instead of storing a second copy.
 *
 * [senderId] is set by the gateway from the authenticated session, never taken from the client
 * frame — which is why this endpoint must stay unreachable from outside the cluster.
 */
data class SendMessageRequest(

    @field:NotBlank
    @field:Size(max = 64)
    val clientMessageId: String,

    @field:NotBlank
    val chatId: String,

    @field:NotBlank
    val senderId: String,

    @field:NotBlank
    @field:Size(max = 4000)
    val body: String
)