server:
  port: 0

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5434/user
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/relay-realm
          jwk-set-uri: http://localhost:8081/realms/relay-realm/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

relay:
  user:
    avatar:
      max-size: 1MB
      allowed-content-types:
        - image/png
        - image/jpeg
        - image/webp
        - image/gif

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.relay: DEBUG
    root: INFO