-- Baseline for the call service schema.
--
-- Unlike the message and notification baselines, nothing preceded this one — `call` had no
-- entities and no datasource before signaling shipped, so this is the schema's first state rather
-- than a capture of what `ddl-auto: update` had accumulated. From here it moves only through
-- migrations, and `ddl-auto: validate` holds the entities to it.
--
-- Constraint names are spelled out for the same reason as elsewhere: a later migration that has to
-- drop one should not have to guess at a Hibernate-generated name.

-- One row per call. Statuses are the ones docs/PROTOCOL.md §4.4 names:
-- initiated | ringing | answered | rejected | missed | ended.
--
-- `id` is generated by the *client*, not here. The caller's trickle ICE starts arriving before any
-- server round trip could hand an id back, so candidates need one that exists immediately — and a
-- repeated id makes a retried invite a primary-key collision the service answers with the call it
-- already stored, which is the same idempotency discipline as `uk_messages_sender_client_id`.
--
-- `dialog_id` carries no foreign key and is never validated: dialogs live in message-service's
-- database, which this service cannot see and must not try to. It is stored purely so a client can
-- correlate a call with a conversation.
--
-- `version` backs JPA optimistic locking. It is what makes two devices answering the same call at
-- the same moment resolve to one winner instead of one silently overwriting the other.
CREATE TABLE calls (
    id          uuid                        NOT NULL,
    dialog_id   uuid,
    initiator   varchar(64)                 NOT NULL,
    type        varchar(8)                  NOT NULL,
    status      varchar(16)                 NOT NULL,
    started_at  timestamp(6) with time zone NOT NULL,
    answered_at timestamp(6) with time zone,
    ended_at    timestamp(6) with time zone,
    duration_s  integer,
    end_reason  varchar(32),
    version     bigint                      NOT NULL DEFAULT 0,
    CONSTRAINT pk_calls PRIMARY KEY (id)
);

-- A participant table rather than caller/callee columns, so group calls need no schema change.
-- Direct calls are held to exactly two participants by the service, not by the schema.
CREATE TABLE call_participants (
    call_id   uuid        NOT NULL,
    user_id   varchar(64) NOT NULL,
    joined_at timestamp(6) with time zone,
    left_at   timestamp(6) with time zone,
    CONSTRAINT pk_call_participants PRIMARY KEY (call_id, user_id),
    CONSTRAINT fk_call_participants_call FOREIGN KEY (call_id) REFERENCES calls (id) ON DELETE CASCADE
);

-- "A user can be in at most one live call" as a primary key rather than an application check.
--
-- Both participants get a row inside the same transaction that creates the call, so a second
-- invite involving either of them fails on the key and is reported as USER_BUSY. That also makes
-- glare — A and B dialling each other in the same instant — resolve without a race: one
-- transaction commits, the other collides. An application-level "is this user busy?" query would
-- let both pass.
--
-- Rows are deleted on every terminal transition (answered calls end, rejected and missed ones
-- release immediately), so this table holds only calls that are ringing or in progress.
CREATE TABLE active_calls (
    user_id varchar(64) NOT NULL,
    call_id uuid        NOT NULL,
    CONSTRAINT pk_active_calls PRIMARY KEY (user_id),
    CONSTRAINT fk_active_calls_call FOREIGN KEY (call_id) REFERENCES calls (id) ON DELETE CASCADE
);

-- The ring-timeout sweeper's query: equality on `status`, range on `started_at`. Both come off
-- this index, which matters because it runs every few seconds forever.
CREATE INDEX ix_calls_status_started_at ON calls (status, started_at);

-- The call log is read per participant, newest first. `call_participants` gives the membership,
-- and this index orders the join's other side without a sort.
CREATE INDEX ix_calls_started_at ON calls (started_at DESC, id);
