package com.relay.websocket.protocol

import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 * The subprotocol name the client must send first in `Sec-WebSocket-Protocol`, followed by
 * the access token: `new WebSocket(url, ["access_token", jwt])`. Keeping the token out of the
 * URL keeps it out of access logs and browser history.
 */
const val ACCESS_TOKEN_PROTOCOL = "access_token"

/**
 * Client to gateway. Adding a subtype here forces every `when` over this hierarchy to handle
 * it, which is how later phases pick up new commands without silently dropping them.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes(
    JsonSubTypes.Type(value = InboundFrame.Ping::class, name = "PING"),
    JsonSubTypes.Type(value = InboundFrame.MessageSend::class, name = "MESSAGE_SEND")
)
sealed interface InboundFrame {

    data class Ping(val nonce: String? = null) : InboundFrame

    /**
     * Note the absence of a sender: it is taken from the authenticated session, never from the
     * frame, so a client cannot send as somebody else.
     *
     * [clientMessageId] is generated by the client and makes the send idempotent, so that if the
     * ack never arrives and the client retries over REST, no duplicate is stored.
     */
    data class MessageSend(
        val clientMessageId: String,
        val chatId: String,
        val body: String
    ) : InboundFrame
}