package com.relay.websocket.protocol

/**
 * The subprotocol name the client must send first in `Sec-WebSocket-Protocol`, followed by
 * the access token: `new WebSocket(url, ["access_token", jwt])`. Keeping the token out of the
 * URL keeps it out of access logs and browser history.
 */
const val ACCESS_TOKEN_PROTOCOL = "access_token"

/**
 * Client to gateway, already unwrapped from the envelope by [FrameCodec]. [id] is the envelope
 * `id` — client-generated, used for correlation and idempotency; [ts] is the client timestamp,
 * advisory only.
 *
 * Adding a subtype forces every `when` over this hierarchy to handle it, which is how later
 * phases pick up new commands without silently dropping them.
 */
sealed interface InboundFrame {

    val id: String?
    val ts: Long?

    data class Ping(
        override val id: String? = null,
        override val ts: Long? = null
    ) : InboundFrame

    /**
     * Note the absence of a sender: it is taken from the authenticated session, never from the
     * frame, so a client cannot send as somebody else. The envelope [id] is the
     * client-generated message id that makes the send idempotent.
     */
    data class MessageSend(
        override val id: String,
        override val ts: Long? = null,
        val dialogId: String,
        val text: String
    ) : InboundFrame

    data class MessageRead(
        override val id: String,
        override val ts: Long? = null,
        val dialogId: String,
        val upToMessageId: String
    ) : InboundFrame

    /**
     * Presence is **subscribe-on-demand**: a client asks for the peers of one conversation when it
     * opens it, and drops them when it closes. Broadcasting every user's presence to all their
     * contacts is what turns a carrier blip into a storm — 50k users reconnecting with 200 contacts
     * each is 10 million frames, and it only happens during an incident.
     *
     * Addressed by dialog rather than by user for the same reason a send is: the client names a
     * conversation it is in, and the server decides which people that is. Naming users directly
     * would let a client watch anybody.
     */
    data class PresenceSubscribe(
        override val id: String,
        override val ts: Long? = null,
        val dialogId: String
    ) : InboundFrame

    data class PresenceUnsubscribe(
        override val id: String,
        override val ts: Long? = null,
        val dialogId: String
    ) : InboundFrame

    /**
     * Typing carries no user — like every other inbound frame, that comes from the session. There is
     * no `typing.stop` counterpart: the indicator expires client-side, so a stop frame lost on a
     * dropped socket cannot leave somebody typing forever.
     */
    data class TypingStart(
        override val id: String,
        override val ts: Long? = null,
        val dialogId: String
    ) : InboundFrame

    /**
     * Call signaling, one subtype per verb — unlike the single opaque `call.signal` frame going the
     * other way. The asymmetry is deliberate: outbound is a relay, so one type is enough, while
     * inbound is a command a state machine has to validate, and `accept` without an SDP should fail
     * at the codec rather than three hops later.
     *
     * [callId] is generated by the *client*. The caller's trickle ICE starts arriving before any
     * round trip could hand an id back, so candidates need one that exists immediately.
     */
    data class CallInvite(
        override val id: String,
        override val ts: Long? = null,
        val callId: String,
        val calleeId: String,
        val media: String,
        val sdp: String,
        val dialogId: String? = null
    ) : InboundFrame

    data class CallAccept(
        override val id: String,
        override val ts: Long? = null,
        val callId: String,
        val sdp: String
    ) : InboundFrame

    data class CallReject(
        override val id: String,
        override val ts: Long? = null,
        val callId: String,
        val reason: String? = null
    ) : InboundFrame

    /** [candidate] is an opaque `RTCIceCandidateInit`; nothing on the server reads inside it. */
    data class CallIce(
        override val id: String,
        override val ts: Long? = null,
        val callId: String,
        val candidate: Map<String, Any?>
    ) : InboundFrame

    data class CallHangup(
        override val id: String,
        override val ts: Long? = null,
        val callId: String,
        val reason: String? = null
    ) : InboundFrame
}